!			VSTADOC utility messages
!			------------------------

! Specify facility prefix and number.
.FACILITY/SYSTEM DOC, 257

! Specify default severity-level
.SEVERITY ERROR

! Entries are of the form
!
!	name		<message> {/FAO=n}
!
! The generated completion code has the global symbol name "VSH_name"
! (because VSH is the specified prefix).  If the error message has variable
! parts to be filled in just after the crime, the /FAO tells how many
! parameters are to be filled in.

! To compile these messages from DCL, say
!
!	$ MESSAGE DOCERRS
!
! To make the messages available to the system, say
!
!	$ LINK DOCERRS
!	$ SET MESSAGE DOCERRS

.PAGE

!
init		<Error initializing VSTADOC>
cmdproc		<Error processing VSTADOC command>
initvt100	<Error initializing VT100 module>
setscroll	<Error setting scroll region on terminal>
header		<Error writing terminal screen>
cantreadcmd	<Error reading program command>
setpos		<Error setting terminal cursor position>
getpos		<Error getting terminal cursor position>
writestr	<Error writing text to terminal screen>
writecrlf	<Error writing blank lines to terminal screen>
parse_error	<Parse error>
argreq		<Argument required on switch, format is: /SWITCH=arg>
nyi		<Function is not yet implemented>
cantdisp	<Can't display page on ONYX screen>
cantgenfil	<Can't generate encoded document file from source>
cantsetview	<Can't setup to VIEW the encoded document file>
noview		<VSTADOC view database not set up>
noidx		<There is no index in this document>
notoc		<There is no table of contents in this document>
hibodypag	<There are only !SL pages in document body> /FAO=1
hiidxpag	<There are only !SL pages in document index> /FAO=1
hitocpag	<There are only !SL pages in document table of contents> /FAO=1
cant_dclexh	<Can't declare exit handler>
cant_open_src	<Can't open source file !AS> /FAO=1
cant_open_list	<Can't open list file !AS> /FAO=1
cant_open_out	<Can't open output file !AS> /FAO=1
cant_open_edf	<Can't open encoded document file !AS> /FAO=1
cant_open_rvw	<Can't open REVIEW file !AS> /FAO=1
rms_open_fai	<RMS $OPEN failed>
rms_create_fai	<RMS $CREATE failed>
rms_cnt_fai	<RMS $CONNECT failed>
cant_close_src	<Can't CLOSE source file !AS> /FAO=1
cant_close_lis	<Can't CLOSE listing file !AS> /FAO=1
cant_close_out	<Can't CLOSE output file !AS> /FAO=1
cant_close_edf	<Can't CLOSE encoded document file !AS> /FAO=1
cant_close_rvw	<Can't CLOSE REVIEW file !AS> /FAO=1
fil_write_error	<Error writing file !AS> /FAO=1
fil_read_error	<Error reading file !AS> /FAO=1
cant_get_forn	<Can't get "foreign" command>
valreq_out	<Value required for /OUTPUT>
valreq_lang	<Value required for /LANGUAGE>
no_src_spec	<No source file specified>
bug		<Bug: in source - doc$_bug, !ZW> /FAO=1
.END
