
.FACILITY	LOGIN,211 /SYSTEM /PREFIX=LGI$_
.SEVERITY	FATAL			! Default severity is fatal
jbcmixup	"fatal job controller interaction problem"
logdisabl	"logins are currently disabled - try again later"
exquota		"maximum number of users exceeded - try again later"
clifail		"error activating command interpreter !AS"/FAO=1
cliprot		"error protecting command interpreter pages"
clisymtbl	"error creating space for command interpreter symbol table"
notvalid	"user authorization failure"
fileacc		"error accessing system authorization file"
userauth	"error accessing authorization record"
inputerr	"error opening primary input file SYS$INPUT"
outputerr	"error opening primary output file SYS$OUTPUT"
cmdinput	"error reading command input"
openin		"error opening !AS as input"/FAO=1 /WARNING
captive		"qualifier not allowed in captive accounts"
badhour		"you are not authorized to login at this time"
userexc		"you are at maximum allowed processes for your user name"
acntexc		"you are at maximum allowed processes for your account name"
nodialin	"you are not authorized to login on a dial in line today"
noremote	"you are not authorized to login via set host today"
.END
