!---
!
!	Error messages for LOGINOUT
!
! Version:	'V04-000'
!
!---

!++
! FACILITY:  LOGINOUT
!
! ABSTRACT:
!
!	These are the error messages used by the LOGINOUT program.
!
! ENVIRONMENT:
!
!	VAX/VMS operating system, privileged utility.
!
!----

.FACILITY	LOGIN,211 /SYSTEM /PREFIX=LGI$_

.SEVERITY	FATAL			! Default severity is fatal

jbcmixup	"fatal job controller interaction problem"
logdisabl	"logins are currently disabled - try again later"
exquota		"maximum number of users exceeded - try again later"
clifail		"error activating command interpreter !AS"/FAO=1
cliprot		"error protecting command interpreter pages"
clisymtbl	"error creating space for command interpreter symbol table"
notvalid	"user authorization failure"
fileacc		"error accessing system authorization file"
userauth	"error accessing authorization record"
inputerr	"error opening primary input file SYS$INPUT"
outputerr	"error opening primary output file SYS$OUTPUT"
cmdinput	"error reading command input"
openin		"error opening !AS as input"/FAO=1 /WARNING
captive		"qualifier not allowed in captive accounts"
badhour		"you are not authorized to login at this time"
userexc		"you are at maximum allowed processes for your user name"
acntexc		"you are at maximum allowed processes for your account name"
badday		"you are not authorized to login today"
restrict	"you are not authorized to login from this source"
netuafacc	"error accessing network authorization file"
syspwdtmo	"system password timeout"
evade		"breakin evasion in effect"
defcli		"you are not authorized to specify CLI parameters"
acntexpir	"your account has expired - contact your system manager"
pwdexpir	"your password has expired - contact your system manager"
connerr		"error connecting to !AS"/FAO=1 /ERROR
disreconnect	"you are not authorized to do reconnections"
clitblfail	"error activating command interpreter tables !AS"/FAO=1
clitblprot	"error protecting command interpreter tables pages"
nosuchuser	"no such user"
invpwd		"invalid password"

.END
