!		VAXstation Stubs software completion codes
!		-------------------------------------
!
!++
! FACILITY:
!   VAX WORKSTATION SOFTWARE
!
! ABSTRACT:
!
!   This module contains the VSTA error codes which are used only by the
!   shareable image library stubs: VSTASTUB and CGLSTUB. They are kept here
!   to minimize the amount of space required to house the stubs on a system
!   where no "real" VAXstation software exists.
!
! ENVIRONMENT:
!   VAX workstation: 780, 750, 730 running VMS with at least one
!   VAXstation system.
!
!--
!


! Specify facility prefix and number. (Declared here AND in the real error
! message file for VSTASHR, etc.).
.FACILITY/SYSTEM/MACRO=$VSTAMSG VSTA, 256
.BASE	0

! Entries are of the form
!
!	name		<message> [/FAO=n]
!
! The generated completion code has the global symbol name "VSTA$_name"
! (because VSTA is the specified prefix).  If the error message has variable
! parts to be filled in just after the crime, the /FAO tells how many
! parameters are to be filled in.
!
! Specify severity-level for internal errors, hardware errors, etc.
.SEVERITY FATAL
.PAGE

!
! *** Error for explicitly logging internal VAXstation Software errors ***
!
notinstal	<VAXstation Software NOT installed on this system>

.END
